TOOLTIP_TEXT = {
    "compress_input_btn": "Select a single PDF file or a folder containing multiple PDFs.",
    "compress_input_entry": "Path to the source PDF file or folder.",
    "compress_output_btn": "Select the destination for the processed file(s).",
    "compress_output_entry": "Path for the output file or folder.",
    "compress_op_combo": "Select the desired compression level preset.",
    "compress_dpi_entry": "Sets the target resolution (DPI) for images.",
    "compress_adv_check": "Show/Hide advanced settings for finer control over the output.",
    "compress_dark_mode_check": "Toggles between light and dark themes.",
    "compress_process_btn": "Start processing the selected file(s) with the current settings.",
    "adv_optimize_images": "Use zlib and sam2p to optimize embedded images (PNG, JPEG) for smaller file sizes.",
    "adv_gs_downscale_factor": "Reduces image dimensions by this factor. '2' = half width/height.",
    "adv_gs_color_conversion": "'Gray' creates a grayscale PDF.",
    "adv_gs_downsample_method": "'Bicubic' provides higher quality downsampling but is slower.",
    "adv_gs_fast_web_view": "Optimizes the PDF for faster loading in web browsers.",
    "adv_gs_subset_fonts": "Reduces file size by embedding only the characters used from each font.",
    "adv_gs_compress_fonts": "Applies compression to all embedded fonts in the document.",
    "adv_gs_remove_interactive": "Strips all interactive elements like comments, links, and form fields.",
    "adv_final_rotation": "Apply a rotation to all pages in the document.",
    "adv_final_precision": "Controls the number of decimal places for coordinates. Lower values can reduce size for vector-heavy PDFs.",
    "adv_final_strip_meta": "Strips all metadata (Title, Author, etc.) from the final document.",
    "adv_final_overwrite": "WARNING: Replaces original files with the processed versions. This cannot be undone.",
    "adv_final_cpdf_squeeze": "Use cpdf's '-squeeze' command for extra compression. Pikepdf options will be ignored.",
    "adv_final_cpdf_darken": "Make text pure black. Useful for scanned documents. Requires cpdf.",
    "adv_final_cpdf_fast": "Use cpdf's '-fast' option for quicker processing. May result in slightly larger files.",
    "adv_sec_user_pass": "Set a password required to open the PDF.",
    "adv_sec_owner_pass": "Set a password required to change permissions or edit the PDF.",
    "adv_sec_show_pass": "Toggle visibility of the entered passwords.",
    "adv_pike_slider": "Pikepdf stream compression level (0=None, 9=Max). This setting is IGNORED if any cpdf option (squeeze, darken text, passwords) is enabled.",
    "merge_add_btn": "Add PDF files to the merge list.",
    "merge_remove_btn": "Remove the selected file from the list.",
    "merge_up_btn": "Move the selected file up in the merge order.",
    "merge_down_btn": "Move the selected file down in the merge order.",
    "merge_output_btn": "Select the file path for the merged PDF.",
    "merge_output_entry": "File path for the final merged PDF.",
    "merge_process_btn": "Combine all files in the list into a single PDF.",
    "split_input_btn": "Select the PDF file to split.",
    "split_input_entry": "Path to the source PDF to be split.",
    "split_mode_combo": "Choose how to split the PDF.",
    "split_value_entry": "For 'N Pages' mode, enter N. For 'Custom', enter ranges (e.g., 1-3, 5, 8-end).",
    "split_output_dir_btn": "Select the folder where split files will be saved.",
    "split_output_dir_entry": "Folder where the split PDFs will be saved.",
    "split_process_btn": "Start the splitting process.",
    "rotate_input_btn": "Select the PDF file to rotate.",
    "rotate_input_entry": "Path of the PDF to rotate.",
    "rotate_angle_combo": "Select the angle to rotate all pages.",
    "rotate_output_btn": "Select the save location for the rotated PDF.",
    "rotate_output_entry": "File path for the rotated PDF.",
    "rotate_process_btn": "Apply the rotation to the PDF.",
    "delete_input_btn": "Select the PDF to delete pages from.",
    "delete_input_entry": "Path of the source PDF.",
    "delete_pages_entry": "Enter pages or ranges to delete (e.g., 1, 3-5, 8-end).",
    "delete_output_btn": "Select the save location for the edited PDF.",
    "delete_output_entry": "File path for the PDF with pages removed.",
    "delete_process_btn": "Start the page deletion process.",
    "convert_input_btn": "Select the PDF to convert to images.",
    "convert_input_entry": "Path of the source PDF.",
    "convert_output_btn": "Select the folder to save the output images.",
    "convert_output_entry": "Folder to save the output images.",
    "convert_format_combo": "Choose the output image format.",
    "convert_dpi_entry": "Dots Per Inch (resolution) for the output images.",
    "convert_process_btn": "Start the PDF to image conversion.",
    "pdfa_input_btn": "Select the PDF to convert to PDF/A format.",
    "pdfa_input_entry": "Path of the source PDF.",
    "pdfa_output_btn": "Select the save location for the PDF/A file.",
    "pdfa_output_entry": "File path for the output PDF/A.",
    "pdfa_process_btn": "Start the PDF/A conversion (for archival).",
    "util_input_btn": "Select a PDF for utility functions.",
    "util_input_entry": "Path of the source PDF.",
    "util_process_btn": "Removes 'OpenAction' flags (e.g., auto-print). Overwrites the input file.",
    "meta_input_btn": "Select a PDF to view or edit its metadata.",
    "meta_input_entry": "Path of the PDF to edit.",
    "meta_load_btn": "Load metadata from the selected PDF.",
    "meta_title": "Edit the document title.",
    "meta_author": "Edit the document author.",
    "meta_subject": "Edit the document subject.",
    "meta_keywords": "Edit the document keywords (comma-separated).",
    "meta_save_btn": "Save the changes to the PDF file (overwrites).",
    "stamp_input_btn": "Select the PDF file to apply a stamp or watermark to.",
    "stamp_input_entry": "Path of the source PDF.",
    "stamp_image_radio": "Apply an image as a stamp.",
    "stamp_text_radio": "Apply text as a stamp/watermark.",
    "stamp_image_btn": "Select the image file (PNG with transparency is recommended).",
    "stamp_image_entry": "Path to the stamp image file.",
    "stamp_image_width": "Set width in pixels. Leave blank for original.",
    "stamp_image_height": "Set height in pixels. Leave blank for original.",
    "stamp_text_entry": "Enter the text for the watermark.",
    "stamp_font_combo": "Select the font for the text stamp.",
    "stamp_font_size": "Set the font size for the text stamp.",
    "stamp_color_btn": "Pick a color for the text stamp.",
    "stamp_dyn_filename": "Add the source filename to the stamp.",
    "stamp_dyn_datetime": "Add the current date and time to the stamp.",
    "stamp_dyn_bates_check": "Add sequential Bates numbering across pages.",
    "stamp_dyn_bates_entry": "Set the starting number for Bates numbering.",
    "stamp_pos_combo": "Set the position of the stamp on the page.",
    "stamp_opacity_slider": "Set the transparency of the stamp (0.1=faint, 1.0=solid).",
    "stamp_ontop_check": "Place the stamp over the page content (watermark) or under it (background).",
    "stamp_output_btn": "Select the save location for the stamped PDF.",
    "stamp_output_entry": "File path for the stamped PDF.",
    "stamp_process_btn": "Apply the stamp to the PDF."
}